---
- name: Install dependencies
  hosts: all
  gather_facts: false
  tasks:
    # - name: SSH into the ASE server using bastion
    #  delegate_to: localhost
    #  ansible.builtin.shell: |
    #    SSH -J root@"{{ item.0 }}" root@"{{ item.1 }}"
    #  changed_when: false
    #  loop: "{{ groups['bastions'] | zip(groups['servers']) | list }}"
    - name: Install dependencies using yum
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      changed_when: false
      with_items:
        - "{{ packages }}"
      retries: 2
